Repository csdojo-defaang/defaang, pull requests merged in 2022-09, with the labels that each got.

#158 feat(header): replace header user menu with avatar button
  package-lock.json
  package.json
  src/components/Header/Header.tsx
  src/components/Header/UserMenu.tsx
  src/components/Header/index.ts
  src/utils/auth.ts
Labels: enhancement

#162 dx: update issue and PR templates
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/doc.yml
  .github/ISSUE_TEMPLATE/dx.yml
  .github/ISSUE_TEMPLATE/features.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/pr-title-checker-config.json
Labels: dx

#161 feat: improve type-safety, cleanup, and add questions route
  .eslintrc.json
  next.config.js
  public/bg_img.webp
  public/logo.svg
  src/components/Header/Header.tsx
  src/components/QuestionSubmissionForm.tsx
  src/components/SignIn/Social.tsx
  src/components/SignUp/Social.tsx
  src/lib/types.ts
  src/pages/_app.tsx
  src/pages/confirm-email.tsx
  src/pages/index.tsx
  src/pages/questions/[id].tsx
  src/pages/questions/index.tsx
  src/pages/questions/new.tsx
  src/pages/signin.tsx
  src/pages/signup.tsx
  src/pages/submit.tsx
Labels: feat

#165 dx: update deps, validate env vars, and set jsonc formatter
  .vscode/settings.json
  next.config.js
  package-lock.json
  package.json
  src/components/Header/Header.tsx
  src/components/Header/UserMenu.tsx
  src/lib/images.d.ts
  src/pages/signin.tsx
  src/pages/signup.tsx
  src/utils/supabaseClient.ts
  tsconfig.json
Labels: dx, refactor

#164 style: improve question submission form UI
  src/components/QuestionSubmissionForm.tsx
  supabase.sql
Labels: style

#226 Link for readme updated
  README.md
Labels: title needs formatting
